language: php
php:
- '7.2'
before_script:
- if find . -name "*.php" ! -path "./vendor/*" -exec php -l {} \; | grep -v "No syntax
  errors detected"; then exit 1; fi
script:
- curl -s -O https://raw.githubusercontent.com/jackthehack21/Bounty/master/travis.sh
- chmod u+x travis.sh
- "./travis.sh"
