---
name: Bounty
author: Jackthehaxk21
version: 1.0.2
api:
- 3.0.0
- 3.1.2
main: Jack\Bounty\Main
commands:
  bounty:
    description: "Bounty command"
    permission: bounty
    usage: /bounty help

permissions:
  bounty:
    default: true
    description: "Allows usage of /bounty"
...
