---
name: Bounty
author: Jackthehaxk21
version: 1.0.3
api:
- 3.0.0
main: Jack\Bounty\Main
depend: [EconomyAPI]
commands:
  bounty:
    description: "Bounty command"
    permission: bounty
    usage: /bounty help

permissions:
  bounty:
    default: true
    description: "Allows usage of /bounty"
...
