---
name: Bounty
main: Jack\Bounty\Main
author: JaxkDev
version: 2.0.0
api: 3.7.0
extensions:
  core: ">=7.4" #aka PHP Version.

depend: [EconomyAPI]

commands:
  bounty:
    description: "Bounty command"
    permission: bounty.cmd
    usage: /bounty help

permissions:
  bounty:
    default: false
    description: "Bounty permissions."
    children:
      bounty.cmd:
        description: "Allows general usage of /bounty"
        default: true
      bounty.new:
        description: "Allows player to add bounties."
        default: true
      bounty.rem:
        description: "Allows player to remove bounties."
        default: op
      bounty.claim:
        description: "Allows player to claim bounties"
        default: true
...
