---
name: Bounty
author: Jackthehaxk21
version: 1.1.0
api:
- 3.7.0
main: Jack\Bounty\Main
commands:
  bounty:
    description: "Bounty command"
    permission: bounty
    usage: /bounty help

permissions:
  bounty:
    default: true
    description: "Allows usage of /bounty"
...
