---
name: Bounty
main: JaxkDev\Bounty\Main
src-namespace-prefix: JaxkDev\Bounty
author: JaxkDev
version: 2.0.0
api: 5.0.0

commands:
  bounty:
    description: "Bounty command"
    permission: bounty.cmd
    usage: /bounty help

permissions:
  bounty:
    default: false
    description: "Bounty permissions."

  bounty.cmd:
    description: "Allows general usage of /bounty"
    default: true
  bounty.cmd.new:
    description: "Allows player to add bounties."
    default: true
  bounty.cmd.rem:
    description: "Allows player to remove bounties."
    default: op

  bounty.claim:
    description: "Allows player to claim bounties"
    default: true

  bounty.immune:
    description: "Allows player to be immune to bounties"
    default: false
...
