---
version: 1

bounty_noperms: "{RED}You do not have permission to do that."

bounty_new_broadcast: "{GOLD}New Bounty on {PLAYER} worth ${AMOUNT}, added by {SENDER}"
bounty_new_success: "{GREEN}Successfully added bounty."
bounty_new_cancelled: "{RED}Bounty addition cancelled."
bounty_new_already: "{RED}That player already has a bounty"
bounty_new_notfound: "{RED}A player with that name cannot be found!"
bounty_new_fundlimit: "{RED}Your bounty amount is not within the limit, (min = {MIN}, max = {MAX})"
bounty_new_funds: "{RED}You dont have enough money to do that :{"

bounty_multiple: true
bounty_multiple_broadcast: "{GOLD}Bounty on {PLAYER} has had ${AMOUNT} added to it by {SENDER}, The new bounty is ${TOTAL}"
bounty_multiple_success: "{GREEN}Successfully added bounty."
bounty_multiple_cancelled: "{RED}Bounty addition cancelled."
bounty_multiple_funds: "{RED}You dont have enough money to do that :{"

bounty_rem_broadcast: "{GOLD}Bounty for {PLAYER} has been removed by {SENDER}"
bounty_rem_success: "{GREEN}Successfully removed bounty."
bounty_rem_cancelled: "{RED}Bounty removal cancelled"
bounty_rem_notfound: "{RED}A player with that name does not have a bounty"

bounty_claim_broadcast: "{GOLD}{SENDER} claimed the bounty on {PLAYER}’s head, worth ${AMOUNT} !"
bounty_claim_success: "{GREEN}Nice one, you claimed the bounty on {PLAYER} worth {AMOUNT}"
bounty_claim_cancelled: "{RED}Bounty claim was cancelled"

bounty_player_join: "{AQUA}{PLAYER} Has joined the server, kill the player to get ${AMOUNT}"
bounty_player_quit: ""

bounty_limit_enforced: true
bounty_min: 1
bounty_max: 1000

leaderboard: true
leaderboard_format: "text"
...